params:
  seed: ${...seed}
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic_dict
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: False

    input_preprocessors:
      ee_pos: {}
      ee_quat: {}
      socket_pos: {}
      socket_quat: {}

    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    rnn:
      name: lstm
      units: 256
      layers: 2
      before_mlp: True
      concat_input: True
      layer_norm: False

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:FactoryTaskInsertion,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1.0e-4
    lr_schedule: fixed  # adaptive?
    schedule_type: standard
    kl_threshold: 0.004
    score_to_win: 20000
    max_epochs: ${resolve_default:1024,${....max_iterations}}
    save_best_after: 50
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 512
    minibatch_size: 512  # batch size = num_envs * horizon_length; minibatch_size = batch_size / num_minibatches
    mini_epochs: 8
    critic_coef: 2
    clip_value: True
    seq_length: 128
    bounds_loss_coef: 0.0001
